server:
  port: 8002
spring:
  application:
    name: business-modular-hi
  zipkin:
    base-url: http://192.168.79.130:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.79.130:8761/eureka/