server:
  port: 8100
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    #    password: null     # 密码,默认密码为空
    timeout: 10000
    database: 0         # Redis数据库索引（默认为0）,如果设置为1，那么存入的key-value都存放在select 1中
    max-wait: 30000     # 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-active: 100     # 连接池最大连接数（使用负值表示没有限制）
    max-idle: 20        # 连接池中的最大空闲连接
    min-idle: 0         # 连接池中的最小空闲连接
    #cluster:           # 集群配置
      #nodes: 127.0.0.1:6381,127.0.0.1:6382,127.0.0.1:6383,127.0.0.1:6384,127.0.0.1:6385,127.0.0.1:6386
      #max-redirects: 2  # 最大重定向次数
  application:
    name: service-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启通过服务中心的自动根据 serviceId 创建路由的功能
      #          lowerCaseServiceId: true
      routes:
        - id: business-modular-feign
          uri: lb://BUSINESS-MODULAR-FEIGN
          order: 0
          predicates:
            - Path=/feign/**
          filters:
            #以下是ip限流配置
            #            - name: RequestRateLimiter
            #              args:
            #                key-resolver: '#{@ipKeyResolver}'
            #                redis-rate-limiter.replenishRate: 200
            #                redis-rate-limiter.burstCapacity: 400
            - name: Hystrix
              args:
                name: fallback
                fallbackUri: forward:/fallback
            - StripPrefix=1
            - AddResponseHeader=X-Response-Default-Foo, Default-Bar
        - id: service-auth
          uri: lb://SERVICE-AUTH
          order: 0
          predicates:
            - Path=/auth/**
          filters:
            - name: Hystrix
              args:
                name: fallback
                fallbackUri: forward:/fallback
            - StripPrefix=1
            - AddResponseHeader=X-Response-Default-Foo, Default-Bar
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.79.130:8761/eureka/
jwt:
  secret: 35713a66d8a9123a119633448cd859a4